session:
 build: ./session/web
 command: python -u app.py
 expose:
  - "5000"
 volumes:
  - ./session/web:/todo
 links:
  - session_db

login:
 build: ./login/web
 command: python -u app.py
 expose:
  - "5000"
 volumes:
  - ./login/web:/todo
 links:
  - login_db
  - session_db

catalog:
 build: ./catalog/web
 command: python -u app.py
 expose:
  - "5000"
 volumes:
  - ./catalog/web:/todo
 links:
  - catalog_db

#The only container accessible from the host
player:
 build: ./player/web
 command: python -u app.py
 ports:
  - "80:5000"
 volumes:
  - ./player/web:/todo
 links:
  - catalog_db
  - login
  - catalog
  - session  

login_db:
 image: mongo:3.0.2
 volumes:
  - ./login/mongo/data:/data/db:rw
  - ./login/mongo/import:/home

catalog_db:
 image: mongo:3.0.2
 volumes:
  - ./catalog/mongo/data:/data/db:rw
  - ./catalog/mongo/import:/home

session_db:
 image: redis:latest
 expose:
  - "6379"